version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_sistema
    restart: always
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: sistema-pedidos
    container_name: spring_sistema
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: